name: gamekit

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++11
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  gamekit:
    type: tool
    platform: macOS
    sources:
        - path: tools/
          type: folder
        - path: build/
          type: folder
        - path: Makefile
        - path: project.yml
        - path: README.md
        - path: scenes/config.h
        - path: gamekit/
          excludes:
            - "deps/"
        - path: gamekit/deps/
          type: folder
        - path: gamekit/deps/gamepad/Gamepad_private.c
        - path: gamekit/deps/gamepad/Gamepad_macosx.c
    dependencies:
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
        - sdk: CoreServices.framework
        - sdk: CoreFoundation.framework
        - sdk: IOKit.framework
    settings:
        HEADER_:SEARCH_PATHS: [$(PROJECT_DIR)/gamekit, $(PROJECT_DIR)/gamekit/deps, $(PROJECT_DIR)/scenes]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL, -fno-objc-arc, -fenable-matrix]
  test:
    type: library.dynamic
    platform: macOS
    sources:
        - path: scenes/test.c
        - path: gamekit/
          excludes:
            - "deps/"
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/gamekit, $(PROJECT_DIR)/gamekit/deps, $(PROJECT_DIR)/scenes]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL, -fno-objc-arc, -fenable-matrix, -DSOKOL_NO_ENTRY, -DGAMEKIT_SCENE]
