name: wee

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++11
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  wee:
    type: application
    info:
      path: Info.plist
    platform: macOS
    sources:
        - path: assets/
          type: folder
        - path: deps/
          type: folder
        - path: tools/
          type: folder
        - path: build/
          type: folder
        - path: include/
        - path: src/
    dependencies:
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
        - sdk: AudioToolbox.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/include, $(PROJECT_DIR)/deps, $(PROJECT_DIR)/build]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL, -fobjc-arc]
