name: wee

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++11
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  wee:
    type: tool
    platform: macOS
    sources:
        - path: assets/
          type: folder
        - path: deps/
          type: folder
        - path: tools/
          type: folder
        - path: build/
          type: folder
        - path: Makefile
        - path: project.yml
        - path: README.md
        - path: game/config.h
        - path: wee.h
        - path: src/
    dependencies:
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR), $(PROJECT_DIR)/deps, $(PROJECT_DIR)/build, $(PROJECT_DIR)/game]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL, -DWEE_DEBUG, -fobjc-arc, -fenable-matrix]
  menu:
    type: library.dynamic
    platform: macOS
    sources:
        - path: game/menu.c
        - path: wee.h
        - path: src/
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR), $(PROJECT_DIR)/deps, $(PROJECT_DIR)/build]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL,-fenable-matrix, -DSOKOL_NO_ENTRY, -DWEE_STATE]
  game:
    type: library.dynamic
    platform: macOS
    sources:
        - path: game/game.c
        - path: wee.h
        - path: src/
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR), $(PROJECT_DIR)/deps, $(PROJECT_DIR)/build]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL,-fenable-matrix, -DWEE_STATE]
